enum class BehaviourType
{
	BEHAVIOUR, 
	
	DRAWABLEBEHAVIOUR,
	PLAYERDRAWABLEBEHAVIOUR,
	ENEMYDRAWABLEBEHAVIOUR,
	GROUNDDRAWABLEBEHAVIOUR,
	GroundObstacleDrawableBehavior,
	MOVEABLEBEHAVIOUR, 
	
	COLLIDABLEBEHAVIOUR
};