enum class EntityType
{
	ACORN, ACTOR, AMMO, BAR, BULLET, DESERTFLOOR, ENEMY, ENTITY, NPC, PLAYER, PLAYERSPRITE, PLANT, PLANTBOSS, GROUND, GROUND2, HEALTH, WEAPON, SHOTGUN, JUMP, CHEATLOAD, GROUNDLVL2, PINGUIN, SNOWMAN, TANK, MECH


};