enum class EntityType
{
	ACORN, ACTOR, AMMO, APC, BAR, BULLET, DESERTFLOOR, ENEMY, ENTITY, NPC, PLAYER, PLAYERSPRITE, PLANT, PLANTBOSS, GROUND, GROUND2, HEALTH, WEAPON, SHOTGUN, CANNON, CANNONSHOT, JUMP, CHEATLOAD, GROUNDLVL2, GROUND2LVL2, PINGUIN, SNOWMAN, MECH, SNOWBOSS, MINIGUNNER, SMALLDESERTFLOOR


};