enum class EntityType
{
ENTITY, ACTOR, NPC, PLAYER, PLAYERSPRITE, ENEMY, PLANT, PLANTBOSS, GROUND, GROUND2, BAR, BULLET, HEALTH, AMMO, WEAPON, SHOTGUN, JUMP, ACORN, CHEATLOAD, GROUNDLVL2, PINGUIN, SNOWMAN, GROUND2LVL2, SNOWBOSS, CANNON, CANNONSHOT, TANK, MECH, APC, DESERTFLOOR, MINIGUNNER

};